### ISSUE TITLE
BUG: Browser Cache after Update

### ISSUE THREAD

**Issue by MrJack91** [PrefectHQ/ui#1050]
**Bug Description**
Some Information are hard cached in the UI (the seconds parts shows the temporarily solution):
* apollo_url -> clear full site data
* list of tasks -> ctrl+f5
* version numbers in the left side panel at the bottom -> ctrl+f5

We had this problem over some upgrades. Not sure when it started, but clients still use the old GUI.

**Steps To Reproduce**
1. upgrade ui (& server) - we use `prefect server start`
  * or change the apollo url in the config.toml
```toml
[server]
  [server.ui]
  apollo_url="https://tst.cdwh.uhbs.ch:443/graphql"
```
2. in the ui you will not see these changes always.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE
